{
 "title": "dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Unified Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$measurement - $tag_zone",
     "query": "SELECT last(\"value\") AS \"Latest Value\"\nFROM \"temperature\", \"humidity\", \"air_quality\", \"light_intensity\"\nWHERE $timeFilter\nGROUP BY \"zone\", \"metric\"\n"
    }
   ]
  },
  {
   "title": "Light Intensity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Light Intensity - $tag_zone",
     "query": "SELECT mean(\"value\") AS \"Light Intensity\"\nFROM \"light_intensity\"\nWHERE $timeFilter\nGROUP BY time($__interval), \"zone\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Air Quality - $tag_zone",
     "query": "SELECT mean(\"value\") AS \"Air Quality\"\nFROM \"air_quality\"\nWHERE $timeFilter\nGROUP BY time($__interval), \"zone\" fill(null)"
    }
   ]
  },
  {
   "title": "Humidity ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity - $tag_zone",
     "query": "SELECT mean(\"value\") AS \"Humidity (%)\"\nFROM \"humidity\"\nWHERE $timeFilter\nGROUP BY time($__interval), \"zone\" fill(null)"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "$tag_zone - $measurement",
     "query": "SELECT mean(\"value\") \nFROM \"temperature\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"zone\"\n"
    }
   ]
  }
 ]
}